spring:
  application:
    name: gateway-service
  main:
    banner-mode: off

zuul:
  prefix: /api
  ignored-services: '*'
  routes:
    place-service:
      path: /place-service/**
      serviceId: place-service
      stripPrefix: true

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.client.eureka-server-port}/eureka/
    eureka-server-port: 8761
  instance:
    hostname: localhost

server:
  port: 8080