spring:
  application:
    name: Discovery Service
  main:
    banner-mode: off

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    enableSelfPreservation: false

server:
  port: 8761
